version: '3.9'

services:
  webserver:
    image: nginx:latest
    container_name: aluilecine_nginx
    volumes:
      - ./default-front.conf:/etc/nginx/conf.d/default.conf
      - ./front:/var/www/html
    depends_on:
      - php-fpm
    network_mode: host  # Utilisation du réseau hôte

  php-fpm:
    image: php:8.2-fpm
    container_name: aluilecine_php-fpm
    volumes:
      - ./front:/var/www/html
    network_mode: host  # Utilisation du réseau hôte

  